# Generated by Django 6.0.3 on 2026-03-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Fresh Produce', 'Fresh Produce'), ('Dairy & Eggs', 'Dairy & Eggs'), ('Meat & Seafood', 'Meat & Seafood'), ('Pantry Staples', 'Pantry Staples'), ('Bakery', 'Bakery'), ('Beverages', 'Beverages'), ('Snacks', 'Snacks'), ('Frozen Foods', 'Frozen Foods'), ('Household', 'Household'), ('Personal Care', 'Personal Care'), ('Organic', 'Organic'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('Fruits & Vegetables', 'Fruits & Vegetables'), ('Dairy & Eggs', 'Dairy & Eggs'), ('Meat & Poultry', 'Meat & Poultry'), ('Grains & Cereals', 'Grains & Cereals'), ('Honey & Preserves', 'Honey & Preserves'), ('Bakery & Pastries', 'Bakery & Pastries'), ('Beverages', 'Beverages'), ('Organic & Specialty', 'Organic & Specialty'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
