# Generated by Django 6.0.3 on 2026-04-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_coupon_store_product_image_store_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='logo',
            new_name='image',
        ),
    ]
